// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SimplePropertyProto.proto

package br.com.six2six.fixturefactory.model.proto;

public final class SimplePropertyProto {
  private SimplePropertyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code br.com.six2six.fixturefactory.model.proto.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HOME = 0;</code>
     */
    HOME(0, 0),
    /**
     * <code>APARTMENT = 1;</code>
     */
    APARTMENT(1, 1),
    UNRECOGNIZED(-1, -1),
    ;

    /**
     * <code>HOME = 0;</code>
     */
    public static final int HOME_VALUE = 0;
    /**
     * <code>APARTMENT = 1;</code>
     */
    public static final int APARTMENT_VALUE = 1;


    public final int getNumber() {
      if (index == -1) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    public static Type valueOf(int value) {
      switch (value) {
        case 0: return HOME;
        case 1: return APARTMENT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Type(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:br.com.six2six.fixturefactory.model.proto.Type)
  }

  public interface PropertyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:br.com.six2six.fixturefactory.model.proto.Property)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional int32 bedrooms_quantity = 2;</code>
     */
    int getBedroomsQuantity();

    /**
     * <code>optional .br.com.six2six.fixturefactory.model.proto.Address address = 3;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional .br.com.six2six.fixturefactory.model.proto.Address address = 3;</code>
     */
    br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address getAddress();
    /**
     * <code>optional .br.com.six2six.fixturefactory.model.proto.Address address = 3;</code>
     */
    br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.AddressOrBuilder getAddressOrBuilder();

    /**
     * <code>optional .br.com.six2six.fixturefactory.model.proto.Type type = 4;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .br.com.six2six.fixturefactory.model.proto.Type type = 4;</code>
     */
    br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Type getType();
  }
  /**
   * Protobuf type {@code br.com.six2six.fixturefactory.model.proto.Property}
   */
  public  static final class Property extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:br.com.six2six.fixturefactory.model.proto.Property)
      PropertyOrBuilder {
    // Use Property.newBuilder() to construct.
    private Property(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Property() {
      id_ = 0;
      bedroomsQuantity_ = 0;
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Property(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              bedroomsQuantity_ = input.readInt32();
              break;
            }
            case 26: {
              br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.Builder subBuilder = null;
              if (address_ != null) {
                subBuilder = address_.toBuilder();
              }
              address_ = input.readMessage(br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(address_);
                address_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.internal_static_br_com_six2six_fixturefactory_model_proto_Property_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.internal_static_br_com_six2six_fixturefactory_model_proto_Property_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property.class, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int BEDROOMS_QUANTITY_FIELD_NUMBER = 2;
    private int bedroomsQuantity_;
    /**
     * <code>optional int32 bedrooms_quantity = 2;</code>
     */
    public int getBedroomsQuantity() {
      return bedroomsQuantity_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address address_;
    /**
     * <code>optional .br.com.six2six.fixturefactory.model.proto.Address address = 3;</code>
     */
    public boolean hasAddress() {
      return address_ != null;
    }
    /**
     * <code>optional .br.com.six2six.fixturefactory.model.proto.Address address = 3;</code>
     */
    public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address getAddress() {
      return address_ == null ? br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.getDefaultInstance() : address_;
    }
    /**
     * <code>optional .br.com.six2six.fixturefactory.model.proto.Address address = 3;</code>
     */
    public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.AddressOrBuilder getAddressOrBuilder() {
      return getAddress();
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>optional .br.com.six2six.fixturefactory.model.proto.Type type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .br.com.six2six.fixturefactory.model.proto.Type type = 4;</code>
     */
    public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Type getType() {
      br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Type result = br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Type.valueOf(type_);
      return result == null ? br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Type.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (bedroomsQuantity_ != 0) {
        output.writeInt32(2, bedroomsQuantity_);
      }
      if (address_ != null) {
        output.writeMessage(3, getAddress());
      }
      if (type_ != br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Type.HOME.getNumber()) {
        output.writeEnum(4, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (bedroomsQuantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, bedroomsQuantity_);
      }
      if (address_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getAddress());
      }
      if (type_ != br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Type.HOME.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code br.com.six2six.fixturefactory.model.proto.Property}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:br.com.six2six.fixturefactory.model.proto.Property)
        br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.PropertyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.internal_static_br_com_six2six_fixturefactory_model_proto_Property_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.internal_static_br_com_six2six_fixturefactory_model_proto_Property_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property.class, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property.Builder.class);
      }

      // Construct using br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        bedroomsQuantity_ = 0;

        if (addressBuilder_ == null) {
          address_ = null;
        } else {
          address_ = null;
          addressBuilder_ = null;
        }
        type_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.internal_static_br_com_six2six_fixturefactory_model_proto_Property_descriptor;
      }

      public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property getDefaultInstanceForType() {
        return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property.getDefaultInstance();
      }

      public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property build() {
        br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property buildPartial() {
        br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property result = new br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property(this);
        result.id_ = id_;
        result.bedroomsQuantity_ = bedroomsQuantity_;
        if (addressBuilder_ == null) {
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property) {
          return mergeFrom((br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property other) {
        if (other == br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getBedroomsQuantity() != 0) {
          setBedroomsQuantity(other.getBedroomsQuantity());
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int bedroomsQuantity_ ;
      /**
       * <code>optional int32 bedrooms_quantity = 2;</code>
       */
      public int getBedroomsQuantity() {
        return bedroomsQuantity_;
      }
      /**
       * <code>optional int32 bedrooms_quantity = 2;</code>
       */
      public Builder setBedroomsQuantity(int value) {
        
        bedroomsQuantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bedrooms_quantity = 2;</code>
       */
      public Builder clearBedroomsQuantity() {
        
        bedroomsQuantity_ = 0;
        onChanged();
        return this;
      }

      private br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address address_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.Builder, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.AddressOrBuilder> addressBuilder_;
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.Address address = 3;</code>
       */
      public boolean hasAddress() {
        return addressBuilder_ != null || address_ != null;
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.Address address = 3;</code>
       */
      public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address getAddress() {
        if (addressBuilder_ == null) {
          return address_ == null ? br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.getDefaultInstance() : address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.Address address = 3;</code>
       */
      public Builder setAddress(br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
          onChanged();
        } else {
          addressBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.Address address = 3;</code>
       */
      public Builder setAddress(
          br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
          onChanged();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.Address address = 3;</code>
       */
      public Builder mergeAddress(br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address value) {
        if (addressBuilder_ == null) {
          if (address_ != null) {
            address_ =
              br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.newBuilder(address_).mergeFrom(value).buildPartial();
          } else {
            address_ = value;
          }
          onChanged();
        } else {
          addressBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.Address address = 3;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = null;
          onChanged();
        } else {
          address_ = null;
          addressBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.Address address = 3;</code>
       */
      public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.Builder getAddressBuilder() {
        
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.Address address = 3;</code>
       */
      public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.AddressOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_ == null ?
              br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.getDefaultInstance() : address_;
        }
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.Address address = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.Builder, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.AddressOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.Builder, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.AddressOrBuilder>(
                  getAddress(),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }

      private int type_ = 0;
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.Type type = 4;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.Type type = 4;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.Type type = 4;</code>
       */
      public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Type getType() {
        br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Type result = br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Type.valueOf(type_);
        return result == null ? br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.Type type = 4;</code>
       */
      public Builder setType(br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.Type type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:br.com.six2six.fixturefactory.model.proto.Property)
    }

    // @@protoc_insertion_point(class_scope:br.com.six2six.fixturefactory.model.proto.Property)
    private static final br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property();
    }

    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Property>
        PARSER = new com.google.protobuf.AbstractParser<Property>() {
      public Property parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Property(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Property> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Property> getParserForType() {
      return PARSER;
    }

    public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Property getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:br.com.six2six.fixturefactory.model.proto.Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string street = 1;</code>
     */
    java.lang.String getStreet();
    /**
     * <code>optional string street = 1;</code>
     */
    com.google.protobuf.ByteString
        getStreetBytes();

    /**
     * <code>optional string street_number = 2;</code>
     */
    java.lang.String getStreetNumber();
    /**
     * <code>optional string street_number = 2;</code>
     */
    com.google.protobuf.ByteString
        getStreetNumberBytes();

    /**
     * <code>optional .br.com.six2six.fixturefactory.model.proto.GeoLocation geo_location = 3;</code>
     */
    boolean hasGeoLocation();
    /**
     * <code>optional .br.com.six2six.fixturefactory.model.proto.GeoLocation geo_location = 3;</code>
     */
    br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation getGeoLocation();
    /**
     * <code>optional .br.com.six2six.fixturefactory.model.proto.GeoLocation geo_location = 3;</code>
     */
    br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocationOrBuilder getGeoLocationOrBuilder();
  }
  /**
   * Protobuf type {@code br.com.six2six.fixturefactory.model.proto.Address}
   */
  public  static final class Address extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:br.com.six2six.fixturefactory.model.proto.Address)
      AddressOrBuilder {
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      street_ = "";
      streetNumber_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Address(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              street_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              streetNumber_ = s;
              break;
            }
            case 26: {
              br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.Builder subBuilder = null;
              if (geoLocation_ != null) {
                subBuilder = geoLocation_.toBuilder();
              }
              geoLocation_ = input.readMessage(br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(geoLocation_);
                geoLocation_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.internal_static_br_com_six2six_fixturefactory_model_proto_Address_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.internal_static_br_com_six2six_fixturefactory_model_proto_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.class, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.Builder.class);
    }

    public static final int STREET_FIELD_NUMBER = 1;
    private volatile java.lang.Object street_;
    /**
     * <code>optional string street = 1;</code>
     */
    public java.lang.String getStreet() {
      java.lang.Object ref = street_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        street_ = s;
        return s;
      }
    }
    /**
     * <code>optional string street = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStreetBytes() {
      java.lang.Object ref = street_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        street_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STREET_NUMBER_FIELD_NUMBER = 2;
    private volatile java.lang.Object streetNumber_;
    /**
     * <code>optional string street_number = 2;</code>
     */
    public java.lang.String getStreetNumber() {
      java.lang.Object ref = streetNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        streetNumber_ = s;
        return s;
      }
    }
    /**
     * <code>optional string street_number = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStreetNumberBytes() {
      java.lang.Object ref = streetNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streetNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GEO_LOCATION_FIELD_NUMBER = 3;
    private br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation geoLocation_;
    /**
     * <code>optional .br.com.six2six.fixturefactory.model.proto.GeoLocation geo_location = 3;</code>
     */
    public boolean hasGeoLocation() {
      return geoLocation_ != null;
    }
    /**
     * <code>optional .br.com.six2six.fixturefactory.model.proto.GeoLocation geo_location = 3;</code>
     */
    public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation getGeoLocation() {
      return geoLocation_ == null ? br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.getDefaultInstance() : geoLocation_;
    }
    /**
     * <code>optional .br.com.six2six.fixturefactory.model.proto.GeoLocation geo_location = 3;</code>
     */
    public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocationOrBuilder getGeoLocationOrBuilder() {
      return getGeoLocation();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStreetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, street_);
      }
      if (!getStreetNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, streetNumber_);
      }
      if (geoLocation_ != null) {
        output.writeMessage(3, getGeoLocation());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStreetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, street_);
      }
      if (!getStreetNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, streetNumber_);
      }
      if (geoLocation_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getGeoLocation());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code br.com.six2six.fixturefactory.model.proto.Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:br.com.six2six.fixturefactory.model.proto.Address)
        br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.internal_static_br_com_six2six_fixturefactory_model_proto_Address_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.internal_static_br_com_six2six_fixturefactory_model_proto_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.class, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.Builder.class);
      }

      // Construct using br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        street_ = "";

        streetNumber_ = "";

        if (geoLocationBuilder_ == null) {
          geoLocation_ = null;
        } else {
          geoLocation_ = null;
          geoLocationBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.internal_static_br_com_six2six_fixturefactory_model_proto_Address_descriptor;
      }

      public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address getDefaultInstanceForType() {
        return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.getDefaultInstance();
      }

      public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address build() {
        br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address buildPartial() {
        br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address result = new br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address(this);
        result.street_ = street_;
        result.streetNumber_ = streetNumber_;
        if (geoLocationBuilder_ == null) {
          result.geoLocation_ = geoLocation_;
        } else {
          result.geoLocation_ = geoLocationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address) {
          return mergeFrom((br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address other) {
        if (other == br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address.getDefaultInstance()) return this;
        if (!other.getStreet().isEmpty()) {
          street_ = other.street_;
          onChanged();
        }
        if (!other.getStreetNumber().isEmpty()) {
          streetNumber_ = other.streetNumber_;
          onChanged();
        }
        if (other.hasGeoLocation()) {
          mergeGeoLocation(other.getGeoLocation());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object street_ = "";
      /**
       * <code>optional string street = 1;</code>
       */
      public java.lang.String getStreet() {
        java.lang.Object ref = street_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          street_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string street = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStreetBytes() {
        java.lang.Object ref = street_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          street_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string street = 1;</code>
       */
      public Builder setStreet(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        street_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string street = 1;</code>
       */
      public Builder clearStreet() {
        
        street_ = getDefaultInstance().getStreet();
        onChanged();
        return this;
      }
      /**
       * <code>optional string street = 1;</code>
       */
      public Builder setStreetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        street_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object streetNumber_ = "";
      /**
       * <code>optional string street_number = 2;</code>
       */
      public java.lang.String getStreetNumber() {
        java.lang.Object ref = streetNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          streetNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string street_number = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStreetNumberBytes() {
        java.lang.Object ref = streetNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          streetNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string street_number = 2;</code>
       */
      public Builder setStreetNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        streetNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string street_number = 2;</code>
       */
      public Builder clearStreetNumber() {
        
        streetNumber_ = getDefaultInstance().getStreetNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string street_number = 2;</code>
       */
      public Builder setStreetNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        streetNumber_ = value;
        onChanged();
        return this;
      }

      private br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation geoLocation_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.Builder, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocationOrBuilder> geoLocationBuilder_;
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.GeoLocation geo_location = 3;</code>
       */
      public boolean hasGeoLocation() {
        return geoLocationBuilder_ != null || geoLocation_ != null;
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.GeoLocation geo_location = 3;</code>
       */
      public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation getGeoLocation() {
        if (geoLocationBuilder_ == null) {
          return geoLocation_ == null ? br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.getDefaultInstance() : geoLocation_;
        } else {
          return geoLocationBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.GeoLocation geo_location = 3;</code>
       */
      public Builder setGeoLocation(br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation value) {
        if (geoLocationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          geoLocation_ = value;
          onChanged();
        } else {
          geoLocationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.GeoLocation geo_location = 3;</code>
       */
      public Builder setGeoLocation(
          br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.Builder builderForValue) {
        if (geoLocationBuilder_ == null) {
          geoLocation_ = builderForValue.build();
          onChanged();
        } else {
          geoLocationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.GeoLocation geo_location = 3;</code>
       */
      public Builder mergeGeoLocation(br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation value) {
        if (geoLocationBuilder_ == null) {
          if (geoLocation_ != null) {
            geoLocation_ =
              br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.newBuilder(geoLocation_).mergeFrom(value).buildPartial();
          } else {
            geoLocation_ = value;
          }
          onChanged();
        } else {
          geoLocationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.GeoLocation geo_location = 3;</code>
       */
      public Builder clearGeoLocation() {
        if (geoLocationBuilder_ == null) {
          geoLocation_ = null;
          onChanged();
        } else {
          geoLocation_ = null;
          geoLocationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.GeoLocation geo_location = 3;</code>
       */
      public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.Builder getGeoLocationBuilder() {
        
        onChanged();
        return getGeoLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.GeoLocation geo_location = 3;</code>
       */
      public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocationOrBuilder getGeoLocationOrBuilder() {
        if (geoLocationBuilder_ != null) {
          return geoLocationBuilder_.getMessageOrBuilder();
        } else {
          return geoLocation_ == null ?
              br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.getDefaultInstance() : geoLocation_;
        }
      }
      /**
       * <code>optional .br.com.six2six.fixturefactory.model.proto.GeoLocation geo_location = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.Builder, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocationOrBuilder> 
          getGeoLocationFieldBuilder() {
        if (geoLocationBuilder_ == null) {
          geoLocationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.Builder, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocationOrBuilder>(
                  getGeoLocation(),
                  getParentForChildren(),
                  isClean());
          geoLocation_ = null;
        }
        return geoLocationBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:br.com.six2six.fixturefactory.model.proto.Address)
    }

    // @@protoc_insertion_point(class_scope:br.com.six2six.fixturefactory.model.proto.Address)
    private static final br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address();
    }

    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Address(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GeoLocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:br.com.six2six.fixturefactory.model.proto.GeoLocation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double latitude = 1;</code>
     */
    double getLatitude();

    /**
     * <code>optional double longitude = 2;</code>
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code br.com.six2six.fixturefactory.model.proto.GeoLocation}
   */
  public  static final class GeoLocation extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:br.com.six2six.fixturefactory.model.proto.GeoLocation)
      GeoLocationOrBuilder {
    // Use GeoLocation.newBuilder() to construct.
    private GeoLocation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GeoLocation() {
      latitude_ = 0D;
      longitude_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GeoLocation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              latitude_ = input.readDouble();
              break;
            }
            case 17: {

              longitude_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.internal_static_br_com_six2six_fixturefactory_model_proto_GeoLocation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.internal_static_br_com_six2six_fixturefactory_model_proto_GeoLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.class, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.Builder.class);
    }

    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>optional double latitude = 1;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>optional double longitude = 2;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (latitude_ != 0D) {
        output.writeDouble(1, latitude_);
      }
      if (longitude_ != 0D) {
        output.writeDouble(2, longitude_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (latitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (longitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code br.com.six2six.fixturefactory.model.proto.GeoLocation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:br.com.six2six.fixturefactory.model.proto.GeoLocation)
        br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.internal_static_br_com_six2six_fixturefactory_model_proto_GeoLocation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.internal_static_br_com_six2six_fixturefactory_model_proto_GeoLocation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.class, br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.Builder.class);
      }

      // Construct using br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        latitude_ = 0D;

        longitude_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.internal_static_br_com_six2six_fixturefactory_model_proto_GeoLocation_descriptor;
      }

      public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation getDefaultInstanceForType() {
        return br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.getDefaultInstance();
      }

      public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation build() {
        br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation buildPartial() {
        br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation result = new br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation(this);
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation) {
          return mergeFrom((br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation other) {
        if (other == br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation.getDefaultInstance()) return this;
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double latitude_ ;
      /**
       * <code>optional double latitude = 1;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>optional double latitude = 1;</code>
       */
      public Builder setLatitude(double value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double latitude = 1;</code>
       */
      public Builder clearLatitude() {
        
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>optional double longitude = 2;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>optional double longitude = 2;</code>
       */
      public Builder setLongitude(double value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double longitude = 2;</code>
       */
      public Builder clearLongitude() {
        
        longitude_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:br.com.six2six.fixturefactory.model.proto.GeoLocation)
    }

    // @@protoc_insertion_point(class_scope:br.com.six2six.fixturefactory.model.proto.GeoLocation)
    private static final br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation();
    }

    public static br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GeoLocation>
        PARSER = new com.google.protobuf.AbstractParser<GeoLocation>() {
      public GeoLocation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GeoLocation(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<GeoLocation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GeoLocation> getParserForType() {
      return PARSER;
    }

    public br.com.six2six.fixturefactory.model.proto.SimplePropertyProto.GeoLocation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_br_com_six2six_fixturefactory_model_proto_Property_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_com_six2six_fixturefactory_model_proto_Property_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_br_com_six2six_fixturefactory_model_proto_Address_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_com_six2six_fixturefactory_model_proto_Address_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_br_com_six2six_fixturefactory_model_proto_GeoLocation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_br_com_six2six_fixturefactory_model_proto_GeoLocation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031SimplePropertyProto.proto\022)br.com.six2" +
      "six.fixturefactory.model.proto\"\265\001\n\010Prope" +
      "rty\022\n\n\002id\030\001 \001(\005\022\031\n\021bedrooms_quantity\030\002 \001" +
      "(\005\022C\n\007address\030\003 \001(\01322.br.com.six2six.fix" +
      "turefactory.model.proto.Address\022=\n\004type\030" +
      "\004 \001(\0162/.br.com.six2six.fixturefactory.mo" +
      "del.proto.Type\"~\n\007Address\022\016\n\006street\030\001 \001(" +
      "\t\022\025\n\rstreet_number\030\002 \001(\t\022L\n\014geo_location" +
      "\030\003 \001(\01326.br.com.six2six.fixturefactory.m" +
      "odel.proto.GeoLocation\"2\n\013GeoLocation\022\020\n",
      "\010latitude\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(\001*\037\n\004Ty" +
      "pe\022\010\n\004HOME\020\000\022\r\n\tAPARTMENT\020\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_br_com_six2six_fixturefactory_model_proto_Property_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_br_com_six2six_fixturefactory_model_proto_Property_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_com_six2six_fixturefactory_model_proto_Property_descriptor,
        new java.lang.String[] { "Id", "BedroomsQuantity", "Address", "Type", });
    internal_static_br_com_six2six_fixturefactory_model_proto_Address_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_br_com_six2six_fixturefactory_model_proto_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_com_six2six_fixturefactory_model_proto_Address_descriptor,
        new java.lang.String[] { "Street", "StreetNumber", "GeoLocation", });
    internal_static_br_com_six2six_fixturefactory_model_proto_GeoLocation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_br_com_six2six_fixturefactory_model_proto_GeoLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_br_com_six2six_fixturefactory_model_proto_GeoLocation_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}